### ISSUE TITLE
AACAdditionPro

### ISSUE THREAD

**Issue by clrxbl** [Incendo/awesome-minecraft#11]
AACAdditionPro is an anticheat designed to assist AAC. It doesn't seem very useful to add to this list without adding AAC, and I'm not sure what everyone's opinions are on listing premium plugins in this list. (AAC is not opensource & is a paid resource).

AACAdditionPro should either get removed or AAC should be added to the list.

**Comment by Citymonstret** [comment]
I agree. I added it because it got suggested, but it doesn't really fit in.
