### ISSUE TITLE
Missing server software (Yatopia)

### ISSUE THREAD

**Issue by Aberdeener** [Incendo/awesome-minecraft#3]
Good day

Noticed this awesome list is missing one of the best Spigot forks out there; Yatopia.
Would be great to get this added.
Thanks

**Comment by MiniDigger** [comment]
![nice-meme-bro](https://user-images.githubusercontent.com/2185527/105614351-152ccf80-5dc9-11eb-9bc3-53367dae4302.jpg)

**Comment by manul694** [comment]
Unstable and bad core. Use purpur instead
